# Generated by Django 4.1.1 on 2022-09-18 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('non', models.CharField(choices=[('design', 'DESIGN'), ('food', 'FOOD'), ('education', 'EDUCATION'), ('energy', 'ENERGY'), ('technology', 'TECHNOLOGIE'), ('programming', 'PROGRAMMING'), ('health', ' HEALTH'), ('finance', 'FINANCE'), ('money', 'MONEY')], default='technology', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tit', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=200)),
                ('dat_kreye', models.DateField(auto_now_add=True)),
                ('deskripsyon', models.CharField(max_length=400)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='projet_foto/')),
                ('projects', models.ManyToManyField(blank=True, to='folio.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('non', models.CharField(max_length=100)),
                ('siyati', models.CharField(max_length=100)),
                ('imel', models.EmailField(max_length=200)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='profile_foto/')),
                ('telefon', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
