# Generated by Django 4.1.1 on 2022-09-18 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='projects',
            new_name='categorys',
        ),
    ]
