# Generated by Django 3.2.12 on 2022-09-25 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0002_rename_projects_project_categorys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='non',
            field=models.CharField(choices=[('design', 'DESIGN'), ('food', 'FOOD'), ('education', 'EDUCATION'), ('energy', 'ENERGY'), ('technology', 'TECHNOLOGIE'), ('programming', 'PROGRAMMING'), ('health', ' HEALTH'), ('finance', 'FINANCE'), ('money', 'MONEY')], max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
