# Generated by Django 3.2.12 on 2022-10-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0006_auto_20220927_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='non',
            field=models.CharField(choices=[('design', 'DESIGN'), ('food', 'FOOD'), ('education', 'EDUCATION'), ('energy', 'ENERGY'), ('technology', 'TECHNOLOGIE'), ('programming', 'PROGRAMMING'), ('health', ' HEALTH'), ('finance', 'FINANCE'), ('money', 'MONEY')], max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='categorys',
            field=models.ManyToManyField(blank=True, to='folio.Category'),
        ),
    ]
